name: Publish Docker Image to Docker Hub

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build the Docker image 1
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app

      - name: Docker Push 1
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app


      - name: SSH to server GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Tắt và xóa toàn bộ container đang chạy"
            sudo docker kill $(docker ps -q)
            sudo docker rm $(docker ps -a -q)
            
            echo "Xóa toàn bộ images"
            docker rmi $(docker images -a -q)
            
            
            echo "Pull images mới"
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app
            sudo docker run -d -p 4200:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4201:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4202:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4203:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4204:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4205:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4206:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4207:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4208:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest
            sudo docker run -d -p 4209:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest            
            sudo docker run -d -p 4210:4200 ${{ secrets.DOCKER_USERNAME }}/sheryu-frontend-app:latest              
            
            echo "Hoàn thành chế độ"
